apiVersion: v1
kind: Service
metadata:
  name: k8s-springboot-demo
  labels:
    app: k8s-springboot-demo
spec:
  type: NodePort
  ports:
    - port: 8999
      targetPort: 8999
      nodePort: 30090
  selector:
    app: k8s-springboot-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-springboot-demo
  labels:
    app: k8s-springboot-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-springboot-demo
  template:
    metadata:
      labels:
        app: k8s-springboot-demo
    spec:
      containers:
        - name: k8s-springboot-demo
          image: zzeju/k8s-springboot-demo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8999
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 10
            httpGet:
              scheme: HTTP
              port: 8999
              path: /test/alive
