apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: k8s-springboot-demo
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: k8s-springboot-demo
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageValue: 200m