apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: k8s-springboot-demo

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: k8s-springboot-demo
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: AverageValue
          averageValue: 200mi